FROM prom/alertmanager:v0.28.0

COPY alertmanager_data/alertmanager.yml /etc/alertmanager/alertmanager.yml

ENTRYPOINT ["/bin/alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml", "--storage.path=/alertmanager"]
