name: prod_backend

networks:
  backend-net:
  nginx-proxy:
    external: true

volumes:
  postgres-data:
  rabbitmq-data:
  minio_data:

services:  

  backend-prod:
    image: cr.yandex/${CONTAINER_REGISTRY}/backend-prod
    container_name: backend-prod
    ports:
      - 50051:50051
    command: |
      sh -c "alembic -c backend/alembic.ini upgrade head && \
      uvicorn backend.src.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./certs/:/code/backend/certs/
    networks:
      - backend-net
      - nginx-proxy
    restart: "unless-stopped"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-prod
    container_name: rabbitmq-prod
    ports:
      - "5672:5672"
    environment:
      VIRTUAL_HOST: rabbitmq.termeet.tech
      VIRTUAL_PORT: 15672
      LETSENCRYPT_HOST: rabbitmq.termeet.tech
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend-net
      - nginx-proxy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  postgres:
    image: postgres:17-alpine
    container_name: postgres-prod
    env_file:
      - .env
    volumes:
     - postgres-data:/var/lib/postgresql
    networks:
      - backend-net
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 1s

  minio-prod:
    image: minio/minio
    hostname: minio-prod
    container_name: minio-prod
    entrypoint: sh
    command: > 
      -c 'mkdir -p /data/test-bucket
      && minio server /data'
    volumes:
      - minio_data:/data
    env_file:
      - .env
    ports: 
      - 9000:9000
      - 9001:9001
    networks:
      - backend-net
      - nginx-proxy
    environment:
      VIRTUAL_HOST: minio.termeet.tech
      VIRTUAL_PORT: 9001
      LETSENCRYPT_HOST: minio.termeet.tech
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru