name: local_backend

networks:
  backend-net:

volumes:
  postgres_data:

services:  

  backend:
    build: .
    container_name: backend-local
    ports:
      - 8000:8000
    command: |
      sh -c "alembic -c backend/alembic.ini upgrade head && \
      uvicorn backend.src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend/migrations/:/code/backend/migrations/
      - ./backend/docs/openapi.yaml:/code/backend/docs/openapi.yaml
      - ./certs/:/code/backend/certs/
    networks:
      - backend-net
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: backend
          target: /code/backend
          ignore:
          - migrations/
          - docs/openapi.yaml
        - action: rebuild
          path: .env
          target: /code/.env

  postgres:
    image: postgres:17-alpine
    container_name: postgres-local
    env_file:
      - .env
    ports:
     - 5432:5432
    volumes:
     - postgres_data:/var/lib/postgresql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 1s

  maildev:
    image: maildev/maildev
    container_name: maildev-local
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - backend-net
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
