name: prod_backend

networks:
  backend-net:
  nginx-proxy:
    external: true

volumes:
  postgres-data:
  rabbitmq-data:
  minio_data:
  prometheus_data:
  alertmanager_data:
  grafana_data:

services:  

  backend:
    image: cr.yandex/${CONTAINER_REGISTRY}/backend-prod
    container_name: backend-prod
    ports:
      - 50051:50051
    command: |
      sh -c "alembic -c backend/alembic.ini upgrade head && \
      uvicorn backend.src.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./certs/:/code/backend/certs/
    networks:
      - backend-net
      - nginx-proxy
    restart: "unless-stopped"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-prod
    container_name: rabbitmq-prod
    ports:
      - "5672:5672"
    environment:
      VIRTUAL_HOST: rabbitmq.termeet.tech
      VIRTUAL_PORT: 15672
      LETSENCRYPT_HOST: rabbitmq.termeet.tech
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend-net
      - nginx-proxy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  postgres:
    image: postgres:17-alpine
    container_name: postgres-prod
    env_file:
      - .env
    volumes:
     - postgres-data:/var/lib/postgresql
    networks:
      - backend-net
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 1s

  minio-prod:
    image: minio/minio
    hostname: minio-prod
    container_name: minio-prod
    entrypoint: sh
    command: > 
      -c 'mkdir -p /data/test-bucket
      && minio server /data'
    volumes:
      - minio_data:/data
    env_file:
      - .env
    ports: 
      - 9000:9000
      - 9001:9001
    networks:
      - backend-net
      - nginx-proxy
    environment:
      VIRTUAL_HOST: minio.termeet.tech
      VIRTUAL_PORT: 9001
      LETSENCRYPT_HOST: minio.termeet.tech
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru

  alertmanager:
    image: cr.yandex/${CONTAINER_REGISTRY}/alertmanager
    container_name: alertmanager-prod
    env_file:
      - .env
    volumes:
      - alertmanager_data:/alertmanager
    networks:
      - backend-net
    restart: unless-stopped

  prometheus:
    image: cr.yandex/${CONTAINER_REGISTRY}/prometheus
    container_name: prometheus-prod
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - backend-net
    restart: unless-stopped
    depends_on:
      - alertmanager

  grafana:
    image: cr.yandex/${CONTAINER_REGISTRY}/grafana
    container_name: grafana-prod
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: grafana.termeet.tech
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.termeet.tech
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru
      GF_SERVER_ROOT_URL: https://grafana.termeet.tech
      GF_USERS_DEFAULT_THEME: light
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend-net
      - nginx-proxy
    restart: unless-stopped
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter-prod
    pid: host
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/rootfs'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    networks:
      - backend-net
    restart: unless-stopped