name: dev_backend

networks:
  backend-net:
  nginx-proxy:
    external: true

volumes:
  postgres_data:
  rabbitmq-data:

services:  

  backend:
    image: cr.yandex/${CONTAINER_REGISTRY}/backend-dev
    container_name: backend-dev
    command: |
      sh -c "alembic -c backend/alembic.ini upgrade head && \
      uvicorn backend.src.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: backend.termeet-dev.ru
      LETSENCRYPT_HOST: backend.termeet-dev.ru
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru
    volumes:
      - ./certs/:/code/backend/certs/
    networks:
      - backend-net
      - nginx-proxy
    restart: "unless-stopped"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-dev
    container_name: rabbitmq-dev
    ports:
      - "5673:5672"
    environment:
      VIRTUAL_HOST: rabbitmq.termeet-dev.ru
      VIRTUAL_PORT: 15672
      LETSENCRYPT_HOST: rabbitmq.termeet-dev.ru
      LETSENCRYPT_EMAIL: maklakov.daniils@yandex.ru
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend-net
      - nginx-proxy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:17-alpine
    container_name: postgres-dev
    env_file:
      - .env
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 1s
