{
 "title": "Termeet Server & Infrastructure",
 "tags": [
  "termeet",
  "infra",
  "node-exporter"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Загрузка CPU хоста",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Использование RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Свободно на диске (Root)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/host/rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime сервера",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Загрузка CPU во времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Used %"
    }
   ]
  },
  {
   "title": "Сетевой трафик (Сеть I/O)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*\"}[1m]))",
     "legendFormat": "Receive (Rx)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*\"}[1m]))",
     "legendFormat": "Transmit (Tx)"
    }
   ]
  }
 ]
}