openapi: 3.0.0
info:
  title: Termeet API
  version: 1.0.0
  description: API для получения информации о встречах

servers:
  - url: https://termeet.tech/api/
    description: Development server

paths:
  /meet/create:
    post:
      summary: Создать встречу
      description: Создает слоты для встречи по определенным дням и промежутку времени
      tags:
        - Meet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeetCreate"
      responses:
        "201":
          description: Успешный ответ с созданием встречи
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetResponse"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /meet/{hash}/:
    get:
      summary: Получить всю информацию о встрече
      description: Возвращает слоты встречи для выбора, а также уже выбранные участниками
      tags:
        - Meet
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор встречи
      responses:
        "200":
          description: Успешный ответ с основной инфой
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetResponse"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /meet/{hash}/slots:
    post:
      summary: Отправить слоты, выбранные пользователем
      description: Отправляет слоты встречи, которые выбрал пользователь
      tags:
        - Meet
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор встречи
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SlotsUser"
      responses:
        "201":
          description: Успешный ответ с отправкой слотов, выбранных пользователем
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SlotsUser"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    MeetResponse:
      type: object
      required:
        - name
        - hash
        - dataRange
        - slots
      properties:
        name:
          type: string
          description: Название встречи
          example: "Встреча"
        description:
          nullable: true
          type: string
          description: Описание встречи
          example: "Описание встречи"
        link:
          nullable: true
          type: string
          description: Прикрепленная к встрече ссылка
          example: "https://telemost.360.yandex.ru/j/6694975853"
        duration:
          nullable: true
          type: string
          description: Продолжительность встречи
          pattern: "^(0[1-5]):([0-5][0-9])$"
          example: "01:30"
        dataRange:
          type: array
          description: Все слоты для встречи в формате UTC+0. Совпадать не могут.
          example:
            [
              ["2026-12-21Т22:00:00Z", "2026-12-22Т02:00:00Z"],
              ["2026-12-22Т22:00:00Z", "2026-12-23Т02:00:00Z"],
              ["2026-12-24Т22:00:00Z", "2026-12-25Т02:00:00Z"],
            ]
          items:
            type: array
            items:
              type: string
              format: date-time
        hash:
          type: string
          description: Идентификатор встречи
          format: uuid
          example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        slots:
          type: array
          description: Слоты, выбранные пользователями в формате UTC+0. В случае если встреча состоит из одного слота, то время начала совпадает со временем конца
          items:
            $ref: "#/components/schemas/SlotsUser"
          example:
            [
              "Данек":
                [
                  ["2026-12-21Т22:00:00Z", "2026-12-22Т02:00:00Z"],
                  ["2026-12-22Т22:00:00Z", "2026-12-23Т02:00:00Z"],
                ],
              "Кирилл":
                [
                  ["2026-12-21Т22:00:00Z", "2026-12-21Т23:00:00Z"],
                  ["2026-12-23Т00:00:00Z", "2026-12-23Т01:00:00Z"],
                ],
              "Колян": [["2026-12-25Т00:00:00Z", "2026-12-25Т00:00:00Z"]],
            ]

    MeetCreate:
      type: object
      required:
        - name
        - dataRange
      properties:
        name:
          type: string
          description: Название встречи
          example: "Встреча"
        description:
          nullable: true
          type: string
          description: Описание встречи
          example: "Описание встречи"
        link:
          nullable: true
          type: string
          description: Прикрепленная к встрече ссылка
          example: "https://telemost.360.yandex.ru/j/6694975853"
        duration:
          nullable: true
          type: string
          description: Продолжительность встречи
          pattern: "^(0[1-5]):([0-5][0-9])$"
          example: "01:30"
        dataRange:
          type: array
          description: Все слоты для встречи в формате UTC+0. Совпадать не могут.
          example:
            [
              ["2026-12-21Т22:00:00Z", "2026-12-22Т02:00:00Z"],
              ["2026-12-22Т22:00:00Z", "2026-12-23Т02:00:00Z"],
              ["2026-12-24Т22:00:00Z", "2026-12-25Т02:00:00Z"],
            ]
          items:
            type: array
            items:
              type: string
              format: date-time

    SlotsUser:
      type: object
      required:
        - name
        - slots
      properties:
        name:
          type: string
          description: Имя пользователя
          example: "Данек"
        slots:
          description: Слоты, выбранные пользователем в формате UTC+0. В случае если встреча состоит из одного слота, то время начала совпадает со временем конца
          type: array
          items:
            type: array
            items:
              type: string
              format: date-time
          example:
            [
              ["2026-12-21Т22:00:00Z", "2026-12-22Т02:00:00Z"],
              ["2026-12-22Т22:00:00Z", "2026-12-23Т02:00:00Z"],
            ]

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Something went wrong"

  responses:
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
