"""Add feedback table

Revision ID: 0e1868abcd09
Revises: 43517ce44bea
Create Date: 2026-05-09 23:42:49.923751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e1868abcd09'
down_revision: Union[str, Sequence[str], None] = '43517ce44bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', postgresql.ENUM('HELP', 'SUGGESTION', 'BUG', 'PARTNERSHIP', 'OTHER', name='feedback_type'), nullable=False),
    sa.Column('communication_channel', postgresql.ENUM('EMAIL', 'TELEGRAM', name='communication_channel'), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
