"""Refactor Users

Revision ID: 1979c8b73d61
Revises: a567bb8b59e2
Create Date: 2026-04-09 16:23:36.168932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1979c8b73d61'
down_revision: Union[str, Sequence[str], None] = 'a567bb8b59e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('additional_emails', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('users', 'additional_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_email', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('users', 'additional_emails')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
