"""add link feedback with user

Revision ID: 227982df7bde
Revises: 0e1868abcd09
Create Date: 2026-05-10 13:55:11.481457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227982df7bde'
down_revision: Union[str, Sequence[str], None] = '0e1868abcd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'user_id')
    # ### end Alembic commands ###
