"""add nickname to users

Revision ID: 2546af58a223
Revises: f5f799165d35
Create Date: 2026-05-02 07:04:07.279896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2546af58a223"
down_revision: Union[str, Sequence[str], None] = "f5f799165d35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "nickname",
            sa.String(length=50),
            sa.Computed(
                "first_name",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
